version: "3"

services:
  app:
    build: .
    image: mnestor/shepherd
    environment:
      APPRISE_SIDECAR_URL: notify:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - notification
    deploy:
      placement:
        constraints:
        - node.role == manager

  notify:
    image: mnestor/apprise-microservice:0.1
    environment:
      NOTIFICATION_URLS: mailtos://user:pass@domain/?to=target@example.com
    networks:
      - notification

networks:
  notification:
